# Generated by Django 4.1.4 on 2023-03-10 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oneapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=oneapp.models.default_datetime, verbose_name='Дата тренировки')),
                ('weight_body', models.FloatField(blank=True, default=80.5, null=True, verbose_name='Вес тела')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Оставьте комментарий', null=True, verbose_name='Комментарий')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='oneapp.day')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Вес снаряда')),
                ('reps', models.IntegerField(default=8, verbose_name='Количество повторений')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='oneapp.exercise', verbose_name='Упражнение')),
            ],
        ),
        migrations.CreateModel(
            name='NameExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Упражнение')),
                ('slug', models.SlugField(unique=True)),
                ('is_present', models.BooleanField(default=False)),
                ('group', models.ForeignKey(help_text='Название мышечной группы', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='oneapp.group', verbose_name='Мышечная группа')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ForeignKey(help_text='Название мышечной группы', on_delete=django.db.models.deletion.CASCADE, to='oneapp.group', verbose_name='Мышечная группа'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_exercise',
            field=models.ForeignKey(help_text='Название упражнения', on_delete=django.db.models.deletion.CASCADE, to='oneapp.nameexercise', verbose_name='Упражнение'),
        ),
    ]
