# Generated by Django 4.1.4 on 2023-03-10 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_number',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='weight_body',
            field=models.FloatField(blank=True, default=80.5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Вес тела'),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество повторений'),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(700)], verbose_name='Вес снаряда'),
        ),
    ]
