# Generated by Django 4.1.4 on 2023-04-07 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0002_exercise_exercise_number_set_set_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_number',
        ),
        migrations.RemoveField(
            model_name='nameexercise',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='set',
            name='set_number',
        ),
        migrations.AlterField(
            model_name='day',
            name='weight_body',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)], verbose_name='Вес тела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество повторений'),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес снаряда'),
        ),
    ]
