# Generated by Django 4.1.4 on 2023-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0003_remove_exercise_exercise_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('author', 'pub_date'), name='unique_author_pub_date'),
        ),
    ]
