# Generated by Django 4.1.4 on 2023-04-07 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0004_day_unique_author_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='weight_body',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)], verbose_name='Вес тела'),
        ),
    ]
